<template>
  <div class="mt-5">
    <router-link
      to="/"
      class="logo d-none d-sm-block text-center mb-5 text-white"
      style="font-size:35px"
    >
      <span class="text-center"><i class="fad fa-mountain"></i> Avaxchain</span
      ><small class="ml-2">/api</small>
    </router-link>
    <div class="card" style="padding:50px">
      <div class="docs-content">
        <div class="docs-title">
          <h2 class="mb-4">Creating payment request</h2>
          <p class="text-muted docs-lead mb-0">
            <pre>
    $ GET | https://api.avamatic.com/orders/create?
    merchant=<b>[MERCHANT_ID]</b>&
    asset_code=<b>[ASSET_CODE]</b>&
    asset_id=<b>[ASSET_ID]</b>&
    item_name=<b>Mocha</b>&
    item_price=<b>0.00000001</b>&
    item_quantity=<b>1</b>
            </pre>
          </p>
          <hr/>
          <h2 class="mb-4">Tracking order</h2>
           <pre>
    $ GET | https://api.avamatic.com/orders/<b>[ORDER_ID]</b></pre>
        <hr/>
        <h2 class="mb-4">Redirecting to Checkout</h2>
        <p>Using Checkout is quite simple. All you have to do is redirect the user to the checkout page with the order id which generated by payment request endpoint.</p>
        <pre>
    $ REDIRECT | http://avamatic.com/checkout/<b>[ORDER_ID]</b></pre>
        <hr/>
        <h2 class="mb-4">Accessing to payment wallets</h2>
        <p>Every order which are belongs to a merchant account has unique derivation paths. You can access your receiving payment addresses via <b>AVA HD Wallet library</b> or via <b>Orders</b> section in your Avaxchain account and can withdraw it.</p>
        <p>Derivation path : <b>m/[merchant_account_id]/[order_index]</b></p>
        
        <hr/>
        <h2><i>Notes</i></h2>
        <p>* If timeout is "true", this indicates that the payment request has timed out. </p>
        <p>* The is_paid value indicates the status of the payment transaction.</p>
        <p>* Payment amount is the result of the product of the item_quantity and item_price variables. item_price should specify the price of one item.</p>
        <p>* Each payment request is valid for 30 minutes.</p>
        </div>
      </div>
    </div>
  </div>
</template>
